### ISSUE TITLE
Add possibility to set _startAngle and _itemSpacing

### ISSUE THREAD

**Issue by baptistesx** [Bdaya-Dev/circular-widgets#2]
I'd like to divide widgets only around the bottom half of a circle.
I checked the code and I think it might be possible to do it if we can pass _startAngle as parameter and change the 360 value in the _itemSpacing formula?
To finally get something like this:
![image](https://user-images.githubusercontent.com/9638281/174072173-0080bfd1-24ff-465e-87dd-4a8c803a3e53.png)

**Comment by ahmednfwela** [comment]
This is definitely doable in this library, I just need to figure out the math for it
will start working on it soon

**Comment by ahmednfwela** [comment]
V 2.1.0 handles this now.
I also added the ability to change draw direction, please check the example project.

**Comment by baptistesx** [comment]
Awesome thanks, I'll check that out !
