### ISSUE TITLE
Allow to choose whether center circle or outer ones first 

### ISSUE THREAD

**Issue by baptistesx** [Bdaya-Dev/circular-widgets#3]
Hey, here is a new little need:
Here is what I need: <img width="185" alt="image" src="https://user-images.githubusercontent.com/9638281/175261186-5a4dd1c7-309e-4d97-af51-02e727c42adb.png"> otherwise, the center circle is over the outer ones.

Change the order of these two lines according to a variable: 
![image](https://user-images.githubusercontent.com/9638281/175261556-7c83937b-e505-4aef-83a9-eb3dc5adac16.png)

**Comment by ahmednfwela** [comment]
I see, will work on it now.

also would you like the next major version to support flutter 3?

**Comment by baptistesx** [comment]
I'll migrate soon to flutter 3 so yes it would be nice :)
